/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_window2 (void);
GtkWidget* create_window3 (void);
GtkWidget* create_window4 (void);
GtkWidget* create_window5 (void);
GtkWidget* create_window6 (void);
GtkWidget* create_window7 (void);
GtkWidget* create_window8 (void);
GtkWidget* create_window9 (void);
GtkWidget* create_window10 (void);
GtkWidget* create_window11 (void);
GtkWidget* create_window12 (void);
GtkWidget* create_Gestion_des_evenements (void);
GtkWidget* create_inscription_membre (void);
GtkWidget* create_AjoutMembreNJ (void);
GtkWidget* create_RechercherMembreNJ (void);
GtkWidget* create_SuppressionMembreNJ (void);
GtkWidget* create_Modifier_membre (void);
GtkWidget* create_AJoutercoach (void);
GtkWidget* create_Modifier_coach (void);
GtkWidget* create_RecherchercoachNJ (void);
GtkWidget* create_supprimer_coachNJ (void);
GtkWidget* create_Menu_Principale (void);
GtkWidget* create_window_navigation (void);
GtkWidget* create_widow_administrateur (void);
GtkWidget* create_window_rechercher (void);
GtkWidget* create_window_modifier (void);
GtkWidget* create_window_supprimer (void);
GtkWidget* create_window_ajouter (void);
GtkWidget* create_window_reserver (void);
GtkWidget* create_window_navigation_entraineur (void);
GtkWidget* create_administrateur_ (void);
GtkWidget* create_ajouter (void);
GtkWidget* create_modifier (void);
GtkWidget* create_rechercher (void);
GtkWidget* create_supprimer (void);
GtkWidget* create_membre (void);
GtkWidget* create_emploi (void);
GtkWidget* create_window20 (void);
