/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

 GtkWidget *window1;
 GtkWidget *window2;
 GtkWidget *window3;
 GtkWidget *window4;
 GtkWidget *window5;
 GtkWidget *window6;
 GtkWidget *window7;
 GtkWidget *window8;
 GtkWidget *window9;
 GtkWidget *window10;
 GtkWidget *window11;
 GtkWidget *window12;
 GtkWidget *window_navigation;
 GtkWidget *Gestion_des_evenements;
 GtkWidget *inscription_membre;
 GtkWidget *window_navigation_entraineur;
 GtkWidget *window_administrateur;
 GtkWidget *window_rechercher;
 GtkWidget *window_modifier;
 GtkWidget *window_supprimer;
 GtkWidget *window_ajouter;
 GtkWidget *window_reserver;
  GtkWidget *window20;
 GtkWidget *administrateur_;
 GtkWidget *membre;
int
main (int argc, char *argv[])
{
/*  GtkWidget *window_ajouter_centre;
  GtkWidget *window_supprimer_centre;
  GtkWidget *window_modifier1_centre;
  GtkWidget *window_modifier2_centre;
  GtkWidget *window_rechercher_centre;
  GtkWidget *window_inscription_centre;
  GtkWidget *window_stats_centre;
  GtkWidget *window_navigation_centre;
  GtkWidget *window_login;
  GtkWidget *window_signup;
  GtkWidget *window_role;
  GtkWidget *window_resultat_centre;
*/

  GtkWidget *AjoutMembreNJ;
  GtkWidget *RechercherMembreNJ;
  GtkWidget *SuppressionMembreNJ;
  GtkWidget *Modifier_membre;
  GtkWidget *AJoutercoach;
  GtkWidget *Modifier_coach;
  GtkWidget *RecherchercoachNJ;
  GtkWidget *supprimercoachNJ;
  GtkWidget *Menu_Principale;
 // GtkWidget *window_navigation;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window1 = create_window1 ();
  window2 = create_window2 ();
  window3 = create_window3 ();
  window4 = create_window4 ();
  window5 = create_window5 ();
  window6 = create_window6 ();
  window7 = create_window7 ();
  window8 = create_window8 ();
  window9 = create_window9 ();
  gtk_widget_show (window9);
  window10 = create_window10 ();
  window11 = create_window11 ();
  window12 = create_window12 ();
  Gestion_des_evenements = create_Gestion_des_evenements ();
  //gtk_widget_show (Gestion_des_evenements);
  inscription_membre = create_inscription_membre ();
  //gtk_widget_show (inscription_membre);
  AjoutMembreNJ = create_AjoutMembreNJ ();
  //gtk_widget_show (AjoutMembreNJ);
  RechercherMembreNJ = create_RechercherMembreNJ ();
 // gtk_widget_show (RechercherMembreNJ);
  SuppressionMembreNJ = create_SuppressionMembreNJ ();
 // gtk_widget_show (SuppressionMembreNJ);
  Modifier_membre = create_Modifier_membre ();
 // gtk_widget_show (Modifier_membre);
  AJoutercoach = create_AJoutercoach ();
 // gtk_widget_show (AJoutercoach);
  Modifier_coach = create_Modifier_coach ();
 // gtk_widget_show (Modifier_coach);
  RecherchercoachNJ = create_RecherchercoachNJ ();
 // gtk_widget_show (RecherchercoachNJ);
  supprimercoachNJ = create_supprimer_coachNJ ();
 // gtk_widget_show (supprimercoachNJ);
  Menu_Principale = create_Menu_Principale ();
 // gtk_widget_show (Menu_Principale);
  window_navigation = create_window_navigation ();
  //gtk_widget_show (window1);
  window_navigation_entraineur=create_window_navigation_entraineur();
  window_administrateur = create_widow_administrateur ();
  window_rechercher = create_window_rechercher ();
  window_modifier = create_window_modifier ();
  window_supprimer = create_window_supprimer ();
  window_ajouter = create_window_ajouter ();
  window_reserver = create_window_reserver ();
  window20 =create_window20();
  administrateur_ = create_administrateur_();
  membre = create_membre();
  
  gtk_main ();
  return 0;
}

