/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry_id_centre;
  GtkWidget *entry_nom_centre;
  GtkWidget *entry_adresse_centre;
  GtkWidget *label8;
  GtkWidget *entry_email;
  GtkWidget *entry_tel;
  GtkObject *spin_capacite_adj;
  GtkWidget *spin_capacite;
  GtkObject *spin_nbr_adj;
  GtkWidget *spin_nbr;
  GtkWidget *btn_retour_ajouter;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label7;
  GtkWidget *label_message_ajouter;
  GtkWidget *btn_ajouter_centre;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label6;
  GtkWidget *combo_type;
  GtkWidget *label65;
  GtkWidget *label66;
  GtkWidget *label67;
  GtkWidget *label2;
  GtkWidget *label4;
  GtkWidget *label24;
  GtkWidget *label600;
  GtkWidget *label64;
  GtkWidget *label1;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview_centre;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry_id_centre = gtk_entry_new ();
  gtk_widget_show (entry_id_centre);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_id_centre, 152, 72);
  gtk_widget_set_size_request (entry_id_centre, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_centre), 8226);

  entry_nom_centre = gtk_entry_new ();
  gtk_widget_show (entry_nom_centre);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_nom_centre, 152, 112);
  gtk_widget_set_size_request (entry_nom_centre, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom_centre), 8226);

  entry_adresse_centre = gtk_entry_new ();
  gtk_widget_show (entry_adresse_centre);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_adresse_centre, 152, 152);
  gtk_widget_set_size_request (entry_adresse_centre, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_adresse_centre), 8226);

  label8 = gtk_label_new (_("Listes des Centres :"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed1), label8, 32, 536);
  gtk_widget_set_size_request (label8, 224, 48);
  gtk_label_set_line_wrap (GTK_LABEL (label8), TRUE);

  entry_email = gtk_entry_new ();
  gtk_widget_show (entry_email);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_email, 152, 200);
  gtk_widget_set_size_request (entry_email, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_email), 8226);

  entry_tel = gtk_entry_new ();
  gtk_widget_show (entry_tel);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_tel, 152, 240);
  gtk_widget_set_size_request (entry_tel, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_tel), 8226);

  spin_capacite_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spin_capacite = gtk_spin_button_new (GTK_ADJUSTMENT (spin_capacite_adj), 1, 0);
  gtk_widget_show (spin_capacite);
  gtk_fixed_put (GTK_FIXED (fixed1), spin_capacite, 144, 288);
  gtk_widget_set_size_request (spin_capacite, 60, 27);

  spin_nbr_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spin_nbr = gtk_spin_button_new (GTK_ADJUSTMENT (spin_nbr_adj), 1, 0);
  gtk_widget_show (spin_nbr);
  gtk_fixed_put (GTK_FIXED (fixed1), spin_nbr, 336, 288);
  gtk_widget_set_size_request (spin_nbr, 60, 27);

  btn_retour_ajouter = gtk_button_new ();
  gtk_widget_show (btn_retour_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), btn_retour_ajouter, 152, 496);
  gtk_widget_set_size_request (btn_retour_ajouter, 112, 48);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (btn_retour_ajouter), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox2), label7, FALSE, FALSE, 0);

  label_message_ajouter = gtk_label_new ("");
  gtk_widget_show (label_message_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), label_message_ajouter, 0, 376);
  gtk_widget_set_size_request (label_message_ajouter, 448, 48);

  btn_ajouter_centre = gtk_button_new ();
  gtk_widget_show (btn_ajouter_centre);
  gtk_fixed_put (GTK_FIXED (fixed1), btn_ajouter_centre, 88, 432);
  gtk_widget_set_size_request (btn_ajouter_centre, 240, 56);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (btn_ajouter_centre), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox1), label6, FALSE, FALSE, 0);

  combo_type = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combo_type);
  gtk_fixed_put (GTK_FIXED (fixed1), combo_type, 128, 336);
  gtk_widget_set_size_request (combo_type, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_type), _("Centre de fitness"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_type), _("Centre d\342\200\231arts martiaux"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_type), _("Centre de danse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_type), _("Centre multisports"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_type), _("Centre de sport de combat"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_type), _("Centre de r\303\251\303\251ducation sportive"));

  label65 = gtk_label_new (_("CAPACITE :"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed1), label65, 16, 283);
  gtk_widget_set_size_request (label65, 160, 40);

  label66 = gtk_label_new (_("NB_SALLES :"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed1), label66, 200, 283);
  gtk_widget_set_size_request (label66, 160, 40);

  label67 = gtk_label_new (_("TYPE :"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed1), label67, 24, 328);
  gtk_widget_set_size_request (label67, 160, 40);

  label2 = gtk_label_new (_("ID : "));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 48, 64);
  gtk_widget_set_size_request (label2, 152, 40);

  label4 = gtk_label_new (_("NOM :"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 40, 104);
  gtk_widget_set_size_request (label4, 152, 40);

  label24 = gtk_label_new (_("ADRESSE :"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed1), label24, 32, 146);
  gtk_widget_set_size_request (label24, 152, 40);

  label600 = gtk_label_new (_("E-MAIL :"));
  gtk_widget_show (label600);
  gtk_fixed_put (GTK_FIXED (fixed1), label600, 32, 192);
  gtk_widget_set_size_request (label600, 160, 40);

  label64 = gtk_label_new (_("TEL :"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed1), label64, 40, 232);
  gtk_widget_set_size_request (label64, 160, 40);

  label1 = gtk_label_new (_("AJOUTER UN CENTRE"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 0, 0);
  gtk_widget_set_size_request (label1, 456, 80);
  gtk_misc_set_padding (GTK_MISC (label1), 3, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed1), scrolledwindow1, 8, 584);
  gtk_widget_set_size_request (scrolledwindow1, 512, 96);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  treeview_centre = gtk_tree_view_new ();
  gtk_widget_show (treeview_centre);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview_centre);
  gtk_widget_set_size_request (treeview_centre, 448, 96);

  g_signal_connect ((gpointer) btn_retour_ajouter, "clicked",
                    G_CALLBACK (on_btn_retour_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_ajouter_centre, "clicked",
                    G_CALLBACK (on_btn_ajouter_centre_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_centre, "row_activated",
                    G_CALLBACK (on_treeview_centre_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry_id_centre, "entry_id_centre");
  GLADE_HOOKUP_OBJECT (window1, entry_nom_centre, "entry_nom_centre");
  GLADE_HOOKUP_OBJECT (window1, entry_adresse_centre, "entry_adresse_centre");
  GLADE_HOOKUP_OBJECT (window1, label8, "label8");
  GLADE_HOOKUP_OBJECT (window1, entry_email, "entry_email");
  GLADE_HOOKUP_OBJECT (window1, entry_tel, "entry_tel");
  GLADE_HOOKUP_OBJECT (window1, spin_capacite, "spin_capacite");
  GLADE_HOOKUP_OBJECT (window1, spin_nbr, "spin_nbr");
  GLADE_HOOKUP_OBJECT (window1, btn_retour_ajouter, "btn_retour_ajouter");
  GLADE_HOOKUP_OBJECT (window1, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");
  GLADE_HOOKUP_OBJECT (window1, label_message_ajouter, "label_message_ajouter");
  GLADE_HOOKUP_OBJECT (window1, btn_ajouter_centre, "btn_ajouter_centre");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, combo_type, "combo_type");
  GLADE_HOOKUP_OBJECT (window1, label65, "label65");
  GLADE_HOOKUP_OBJECT (window1, label66, "label66");
  GLADE_HOOKUP_OBJECT (window1, label67, "label67");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, label24, "label24");
  GLADE_HOOKUP_OBJECT (window1, label600, "label600");
  GLADE_HOOKUP_OBJECT (window1, label64, "label64");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window1, treeview_centre, "treeview_centre");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed2;
  GtkWidget *entry_id_centre;
  GtkWidget *label10;
  GtkWidget *btn_retour_supprimer;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label12;
  GtkWidget *label_message_supprimer;
  GtkWidget *check_supprimer_centre;
  GtkWidget *label9;
  GtkWidget *label13;
  GtkWidget *btn_supprimer_centre;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label15;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview_centre;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2), fixed2);

  entry_id_centre = gtk_entry_new ();
  gtk_widget_show (entry_id_centre);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_id_centre, 152, 88);
  gtk_widget_set_size_request (entry_id_centre, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_centre), 8226);

  label10 = gtk_label_new (_("ID : "));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 48, 80);
  gtk_widget_set_size_request (label10, 152, 40);

  btn_retour_supprimer = gtk_button_new ();
  gtk_widget_show (btn_retour_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed2), btn_retour_supprimer, 176, 312);
  gtk_widget_set_size_request (btn_retour_supprimer, 112, 48);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (btn_retour_supprimer), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox4), label12, FALSE, FALSE, 0);

  label_message_supprimer = gtk_label_new ("");
  gtk_widget_show (label_message_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed2), label_message_supprimer, 8, 176);
  gtk_widget_set_size_request (label_message_supprimer, 448, 48);

  check_supprimer_centre = gtk_check_button_new_with_mnemonic (_("Confirmer la suppression de ce centre\342\200\257"));
  gtk_widget_show (check_supprimer_centre);
  gtk_fixed_put (GTK_FIXED (fixed2), check_supprimer_centre, 88, 128);
  gtk_widget_set_size_request (check_supprimer_centre, 320, 32);

  label9 = gtk_label_new (_("SUPPRIMER UN CENTRE"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 0, 0);
  gtk_widget_set_size_request (label9, 456, 80);
  gtk_misc_set_padding (GTK_MISC (label9), 3, 0);

  label13 = gtk_label_new (_("Listes des Centres :"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 24, 408);
  gtk_widget_set_size_request (label13, 224, 48);
  gtk_label_set_line_wrap (GTK_LABEL (label13), TRUE);

  btn_supprimer_centre = gtk_button_new ();
  gtk_widget_show (btn_supprimer_centre);
  gtk_fixed_put (GTK_FIXED (fixed2), btn_supprimer_centre, 112, 240);
  gtk_widget_set_size_request (btn_supprimer_centre, 240, 56);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (btn_supprimer_centre), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_(" supprimer"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox5), label15, FALSE, FALSE, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed2), scrolledwindow2, 16, 448);
  gtk_widget_set_size_request (scrolledwindow2, 456, 112);

  treeview_centre = gtk_tree_view_new ();
  gtk_widget_show (treeview_centre);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview_centre);
  gtk_widget_set_size_request (treeview_centre, 448, 96);

  g_signal_connect ((gpointer) btn_retour_supprimer, "clicked",
                    G_CALLBACK (on_btn_retour_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) check_supprimer_centre, "toggled",
                    G_CALLBACK (on_check_supprimer_centre_toggled),
                    NULL);
  g_signal_connect ((gpointer) btn_supprimer_centre, "clicked",
                    G_CALLBACK (on_btn_supprimer_centre_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_centre, "row_activated",
                    G_CALLBACK (on_treeview_centre_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, entry_id_centre, "entry_id_centre");
  GLADE_HOOKUP_OBJECT (window2, label10, "label10");
  GLADE_HOOKUP_OBJECT (window2, btn_retour_supprimer, "btn_retour_supprimer");
  GLADE_HOOKUP_OBJECT (window2, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window2, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window2, image4, "image4");
  GLADE_HOOKUP_OBJECT (window2, label12, "label12");
  GLADE_HOOKUP_OBJECT (window2, label_message_supprimer, "label_message_supprimer");
  GLADE_HOOKUP_OBJECT (window2, check_supprimer_centre, "check_supprimer_centre");
  GLADE_HOOKUP_OBJECT (window2, label9, "label9");
  GLADE_HOOKUP_OBJECT (window2, label13, "label13");
  GLADE_HOOKUP_OBJECT (window2, btn_supprimer_centre, "btn_supprimer_centre");
  GLADE_HOOKUP_OBJECT (window2, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window2, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window2, image5, "image5");
  GLADE_HOOKUP_OBJECT (window2, label15, "label15");
  GLADE_HOOKUP_OBJECT (window2, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (window2, treeview_centre, "treeview_centre");

  return window2;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed3;
  GtkWidget *btn_modifier1_centre;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label21;
  GtkWidget *btn_retour_modifier1;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label19;
  GtkWidget *label_message_modifier1;
  GtkWidget *entry_id_centre;
  GtkWidget *label17;
  GtkWidget *label16;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("window3"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window3), fixed3);

  btn_modifier1_centre = gtk_button_new ();
  gtk_widget_show (btn_modifier1_centre);
  gtk_fixed_put (GTK_FIXED (fixed3), btn_modifier1_centre, 112, 200);
  gtk_widget_set_size_request (btn_modifier1_centre, 240, 56);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (btn_modifier1_centre), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox8), label21, FALSE, FALSE, 0);

  btn_retour_modifier1 = gtk_button_new ();
  gtk_widget_show (btn_retour_modifier1);
  gtk_fixed_put (GTK_FIXED (fixed3), btn_retour_modifier1, 184, 264);
  gtk_widget_set_size_request (btn_retour_modifier1, 112, 48);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (btn_retour_modifier1), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox7), label19, FALSE, FALSE, 0);

  label_message_modifier1 = gtk_label_new ("");
  gtk_widget_show (label_message_modifier1);
  gtk_fixed_put (GTK_FIXED (fixed3), label_message_modifier1, 0, 128);
  gtk_widget_set_size_request (label_message_modifier1, 448, 48);

  entry_id_centre = gtk_entry_new ();
  gtk_widget_show (entry_id_centre);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_id_centre, 152, 88);
  gtk_widget_set_size_request (entry_id_centre, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_centre), 8226);

  label17 = gtk_label_new (_("ID : "));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 48, 80);
  gtk_widget_set_size_request (label17, 152, 40);

  label16 = gtk_label_new (_("MODIFIER UN CENTRE"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 0, 0);
  gtk_widget_set_size_request (label16, 456, 80);
  gtk_misc_set_padding (GTK_MISC (label16), 3, 0);

  g_signal_connect ((gpointer) btn_modifier1_centre, "clicked",
                    G_CALLBACK (on_btn_modifier1_centre_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_retour_modifier1, "clicked",
                    G_CALLBACK (on_btn_retour_modifier1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window3, btn_modifier1_centre, "btn_modifier1_centre");
  GLADE_HOOKUP_OBJECT (window3, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window3, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window3, image8, "image8");
  GLADE_HOOKUP_OBJECT (window3, label21, "label21");
  GLADE_HOOKUP_OBJECT (window3, btn_retour_modifier1, "btn_retour_modifier1");
  GLADE_HOOKUP_OBJECT (window3, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window3, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window3, image7, "image7");
  GLADE_HOOKUP_OBJECT (window3, label19, "label19");
  GLADE_HOOKUP_OBJECT (window3, label_message_modifier1, "label_message_modifier1");
  GLADE_HOOKUP_OBJECT (window3, entry_id_centre, "entry_id_centre");
  GLADE_HOOKUP_OBJECT (window3, label17, "label17");
  GLADE_HOOKUP_OBJECT (window3, label16, "label16");

  return window3;
}

GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;
  GtkWidget *fixed4;
  GtkWidget *entry_adresse_centre;
  GtkWidget *entry_nom_centre;
  GtkWidget *label25;
  GtkWidget *label23;
  GtkWidget *label22;
  GtkWidget *entry_email;
  GtkWidget *entry_tel;
  GtkObject *spin_nbr_adj;
  GtkWidget *spin_nbr;
  GtkObject *spin_capacite_adj;
  GtkWidget *spin_capacite;
  GtkWidget *label71;
  GtkWidget *label70;
  GtkWidget *label72;
  GtkWidget *label68;
  GtkWidget *label69;
  GtkWidget *combotype;
  GtkWidget *check_modifier_centre;
  GtkWidget *btn_modifier2_centre;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label29;
  GtkWidget *btn_retour_modifier2;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label28;
  GtkWidget *label_message_modifer2;

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4), _("window4"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window4), fixed4);

  entry_adresse_centre = gtk_entry_new ();
  gtk_widget_show (entry_adresse_centre);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_adresse_centre, 192, 144);
  gtk_widget_set_size_request (entry_adresse_centre, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_adresse_centre), 8226);

  entry_nom_centre = gtk_entry_new ();
  gtk_widget_show (entry_nom_centre);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_nom_centre, 192, 96);
  gtk_widget_set_size_request (entry_nom_centre, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom_centre), 8226);

  label25 = gtk_label_new (_("NOUVELLE ADRESSE :"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed4), label25, 32, 136);
  gtk_widget_set_size_request (label25, 152, 40);

  label23 = gtk_label_new (_("NOUVEAU NOM :"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed4), label23, 40, 88);
  gtk_widget_set_size_request (label23, 152, 40);

  label22 = gtk_label_new (_("MODIFIER UN CENTRE"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed4), label22, 0, 0);
  gtk_widget_set_size_request (label22, 456, 80);
  gtk_misc_set_padding (GTK_MISC (label22), 3, 0);

  entry_email = gtk_entry_new ();
  gtk_widget_show (entry_email);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_email, 192, 192);
  gtk_widget_set_size_request (entry_email, 216, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_email), 8226);

  entry_tel = gtk_entry_new ();
  gtk_widget_show (entry_tel);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_tel, 192, 232);
  gtk_widget_set_size_request (entry_tel, 216, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_tel), 8226);

  spin_nbr_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spin_nbr = gtk_spin_button_new (GTK_ADJUSTMENT (spin_nbr_adj), 1, 0);
  gtk_widget_show (spin_nbr);
  gtk_fixed_put (GTK_FIXED (fixed4), spin_nbr, 336, 280);
  gtk_widget_set_size_request (spin_nbr, 60, 27);

  spin_capacite_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spin_capacite = gtk_spin_button_new (GTK_ADJUSTMENT (spin_capacite_adj), 1, 0);
  gtk_widget_show (spin_capacite);
  gtk_fixed_put (GTK_FIXED (fixed4), spin_capacite, 144, 280);
  gtk_widget_set_size_request (spin_capacite, 60, 27);

  label71 = gtk_label_new (_("CAPACITE :"));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed4), label71, 16, 272);
  gtk_widget_set_size_request (label71, 160, 40);

  label70 = gtk_label_new (_("NB_SALLES :"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed4), label70, 200, 272);
  gtk_widget_set_size_request (label70, 160, 40);

  label72 = gtk_label_new (_("TYPE :"));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed4), label72, 24, 320);
  gtk_widget_set_size_request (label72, 160, 40);

  label68 = gtk_label_new (_("NOUVEAU E-MAIL :"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed4), label68, 32, 184);
  gtk_widget_set_size_request (label68, 160, 40);

  label69 = gtk_label_new (_("TEL :"));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixed4), label69, 80, 224);
  gtk_widget_set_size_request (label69, 160, 40);

  combotype = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combotype);
  gtk_fixed_put (GTK_FIXED (fixed4), combotype, 128, 328);
  gtk_widget_set_size_request (combotype, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combotype), _("Centre de fitness"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combotype), _("Centre d\342\200\231arts martiaux"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combotype), _("Centre de danse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combotype), _("Centre multisports"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combotype), _("Centre de sport de combat"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combotype), _("Centre de r\303\251\303\251ducation sportive"));

  check_modifier_centre = gtk_check_button_new_with_mnemonic (_("Confirmer la modification du centre"));
  gtk_widget_show (check_modifier_centre);
  gtk_fixed_put (GTK_FIXED (fixed4), check_modifier_centre, 56, 376);
  gtk_widget_set_size_request (check_modifier_centre, 320, 32);

  btn_modifier2_centre = gtk_button_new ();
  gtk_widget_show (btn_modifier2_centre);
  gtk_fixed_put (GTK_FIXED (fixed4), btn_modifier2_centre, 112, 480);
  gtk_widget_set_size_request (btn_modifier2_centre, 240, 56);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (btn_modifier2_centre), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox11), label29, FALSE, FALSE, 0);

  btn_retour_modifier2 = gtk_button_new ();
  gtk_widget_show (btn_retour_modifier2);
  gtk_fixed_put (GTK_FIXED (fixed4), btn_retour_modifier2, 176, 544);
  gtk_widget_set_size_request (btn_retour_modifier2, 112, 48);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (btn_retour_modifier2), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox10), label28, FALSE, FALSE, 0);

  label_message_modifer2 = gtk_label_new ("");
  gtk_widget_show (label_message_modifer2);
  gtk_fixed_put (GTK_FIXED (fixed4), label_message_modifer2, 8, 424);
  gtk_widget_set_size_request (label_message_modifer2, 448, 48);

  g_signal_connect ((gpointer) check_modifier_centre, "toggled",
                    G_CALLBACK (on_check_modifier_centre_toggled),
                    NULL);
  g_signal_connect ((gpointer) btn_modifier2_centre, "clicked",
                    G_CALLBACK (on_btn_modifier2_centre_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_retour_modifier2, "clicked",
                    G_CALLBACK (on_btn_retour_modifier2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");
  GLADE_HOOKUP_OBJECT (window4, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window4, entry_adresse_centre, "entry_adresse_centre");
  GLADE_HOOKUP_OBJECT (window4, entry_nom_centre, "entry_nom_centre");
  GLADE_HOOKUP_OBJECT (window4, label25, "label25");
  GLADE_HOOKUP_OBJECT (window4, label23, "label23");
  GLADE_HOOKUP_OBJECT (window4, label22, "label22");
  GLADE_HOOKUP_OBJECT (window4, entry_email, "entry_email");
  GLADE_HOOKUP_OBJECT (window4, entry_tel, "entry_tel");
  GLADE_HOOKUP_OBJECT (window4, spin_nbr, "spin_nbr");
  GLADE_HOOKUP_OBJECT (window4, spin_capacite, "spin_capacite");
  GLADE_HOOKUP_OBJECT (window4, label71, "label71");
  GLADE_HOOKUP_OBJECT (window4, label70, "label70");
  GLADE_HOOKUP_OBJECT (window4, label72, "label72");
  GLADE_HOOKUP_OBJECT (window4, label68, "label68");
  GLADE_HOOKUP_OBJECT (window4, label69, "label69");
  GLADE_HOOKUP_OBJECT (window4, combotype, "combotype");
  GLADE_HOOKUP_OBJECT (window4, check_modifier_centre, "check_modifier_centre");
  GLADE_HOOKUP_OBJECT (window4, btn_modifier2_centre, "btn_modifier2_centre");
  GLADE_HOOKUP_OBJECT (window4, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window4, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window4, image11, "image11");
  GLADE_HOOKUP_OBJECT (window4, label29, "label29");
  GLADE_HOOKUP_OBJECT (window4, btn_retour_modifier2, "btn_retour_modifier2");
  GLADE_HOOKUP_OBJECT (window4, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window4, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window4, image10, "image10");
  GLADE_HOOKUP_OBJECT (window4, label28, "label28");
  GLADE_HOOKUP_OBJECT (window4, label_message_modifer2, "label_message_modifer2");

  return window4;
}

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;
  GtkWidget *fixed5;
  GtkWidget *entry_id_centre;
  GtkWidget *label36;
  GtkWidget *btn_rechercher_centre;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label38;
  GtkWidget *btn_retour_rechercher;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label34;
  GtkWidget *label39;
  GtkWidget *label_message_rechercher;
  GtkWidget *label37;
  GtkWidget *scrolledwindow3;
  GtkWidget *treeview_rechercher_centre;

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5), _("window5"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window5), fixed5);

  entry_id_centre = gtk_entry_new ();
  gtk_widget_show (entry_id_centre);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_id_centre, 152, 88);
  gtk_widget_set_size_request (entry_id_centre, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_centre), 8226);

  label36 = gtk_label_new (_("ID : "));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed5), label36, 48, 80);
  gtk_widget_set_size_request (label36, 152, 40);

  btn_rechercher_centre = gtk_button_new ();
  gtk_widget_show (btn_rechercher_centre);
  gtk_fixed_put (GTK_FIXED (fixed5), btn_rechercher_centre, 112, 200);
  gtk_widget_set_size_request (btn_rechercher_centre, 240, 56);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (btn_rechercher_centre), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("rechercher"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox14), label38, FALSE, FALSE, 0);

  btn_retour_rechercher = gtk_button_new ();
  gtk_widget_show (btn_retour_rechercher);
  gtk_fixed_put (GTK_FIXED (fixed5), btn_retour_rechercher, 176, 264);
  gtk_widget_set_size_request (btn_retour_rechercher, 112, 48);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (btn_retour_rechercher), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox13), label34, FALSE, FALSE, 0);

  label39 = gtk_label_new (_("Listes des Centres :"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed5), label39, 16, 336);
  gtk_widget_set_size_request (label39, 224, 48);
  gtk_label_set_line_wrap (GTK_LABEL (label39), TRUE);

  label_message_rechercher = gtk_label_new ("");
  gtk_widget_show (label_message_rechercher);
  gtk_fixed_put (GTK_FIXED (fixed5), label_message_rechercher, 0, 128);
  gtk_widget_set_size_request (label_message_rechercher, 448, 48);

  label37 = gtk_label_new (_("RECHERCHER UN CENTRE"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed5), label37, 0, 0);
  gtk_widget_set_size_request (label37, 456, 80);
  gtk_misc_set_padding (GTK_MISC (label37), 3, 0);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_fixed_put (GTK_FIXED (fixed5), scrolledwindow3, 8, 376);
  gtk_widget_set_size_request (scrolledwindow3, 440, 112);

  treeview_rechercher_centre = gtk_tree_view_new ();
  gtk_widget_show (treeview_rechercher_centre);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), treeview_rechercher_centre);
  gtk_widget_set_size_request (treeview_rechercher_centre, 448, 96);

  g_signal_connect ((gpointer) btn_rechercher_centre, "clicked",
                    G_CALLBACK (on_btn_rechercher_centre_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_retour_rechercher, "clicked",
                    G_CALLBACK (on_btn_retour_rechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_rechercher_centre, "row_activated",
                    G_CALLBACK (on_treeview_rechercher_centre_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");
  GLADE_HOOKUP_OBJECT (window5, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window5, entry_id_centre, "entry_id_centre");
  GLADE_HOOKUP_OBJECT (window5, label36, "label36");
  GLADE_HOOKUP_OBJECT (window5, btn_rechercher_centre, "btn_rechercher_centre");
  GLADE_HOOKUP_OBJECT (window5, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window5, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window5, image14, "image14");
  GLADE_HOOKUP_OBJECT (window5, label38, "label38");
  GLADE_HOOKUP_OBJECT (window5, btn_retour_rechercher, "btn_retour_rechercher");
  GLADE_HOOKUP_OBJECT (window5, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window5, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window5, image13, "image13");
  GLADE_HOOKUP_OBJECT (window5, label34, "label34");
  GLADE_HOOKUP_OBJECT (window5, label39, "label39");
  GLADE_HOOKUP_OBJECT (window5, label_message_rechercher, "label_message_rechercher");
  GLADE_HOOKUP_OBJECT (window5, label37, "label37");
  GLADE_HOOKUP_OBJECT (window5, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (window5, treeview_rechercher_centre, "treeview_rechercher_centre");

  return window5;
}

GtkWidget*
create_window6 (void)
{
  GtkWidget *window6;
  GtkWidget *fixed6;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkObject *spin_jour_adj;
  GtkWidget *spin_jour;
  GtkObject *spin_mois_adj;
  GtkWidget *spin_mois;
  GtkObject *spin_annee_adj;
  GtkWidget *spin_annee;
  GtkObject *spin_heure_adj;
  GtkWidget *spin_heure;
  GtkObject *spin_minute_adj;
  GtkWidget *spin_minute;
  GtkWidget *label50;
  GtkWidget *label48;
  GtkWidget *label47;
  GtkWidget *label52;
  GtkWidget *entry_id_inscription;
  GtkWidget *label49;
  GtkWidget *label_message_inscription;
  GtkWidget *btn_ajouter_inscription;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label51;
  GtkWidget *label53;
  GtkWidget *btn_retour_inscription;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *combo_specialite;
  GtkWidget *label40;
  GtkWidget *scrolledwindow4;
  GtkWidget *treeview_inscription;
  GtkWidget *combo_nom_centre;
  GtkWidget *entry_adresse_inscription;
  GtkWidget *btn_adresse;
  GtkWidget *image25;

  window6 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window6), _("window6"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window6), fixed6);

  label41 = gtk_label_new (_("NOM DU CENTRE :"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed6), label41, 40, 80);
  gtk_widget_set_size_request (label41, 152, 40);

  label42 = gtk_label_new (_("ADRESSE DU CENTRE :"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed6), label42, 32, 128);
  gtk_widget_set_size_request (label42, 152, 40);

  spin_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spin_jour = gtk_spin_button_new (GTK_ADJUSTMENT (spin_jour_adj), 1, 0);
  gtk_widget_show (spin_jour);
  gtk_fixed_put (GTK_FIXED (fixed6), spin_jour, 152, 296);
  gtk_widget_set_size_request (spin_jour, 60, 27);

  spin_mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spin_mois = gtk_spin_button_new (GTK_ADJUSTMENT (spin_mois_adj), 1, 0);
  gtk_widget_show (spin_mois);
  gtk_fixed_put (GTK_FIXED (fixed6), spin_mois, 232, 296);
  gtk_widget_set_size_request (spin_mois, 60, 27);

  spin_annee_adj = gtk_adjustment_new (2025, 2025, 2050, 1, 10, 10);
  spin_annee = gtk_spin_button_new (GTK_ADJUSTMENT (spin_annee_adj), 1, 0);
  gtk_widget_show (spin_annee);
  gtk_fixed_put (GTK_FIXED (fixed6), spin_annee, 312, 296);
  gtk_widget_set_size_request (spin_annee, 60, 27);

  spin_heure_adj = gtk_adjustment_new (9, 6, 23, 1, 10, 10);
  spin_heure = gtk_spin_button_new (GTK_ADJUSTMENT (spin_heure_adj), 1, 0);
  gtk_widget_show (spin_heure);
  gtk_fixed_put (GTK_FIXED (fixed6), spin_heure, 152, 344);
  gtk_widget_set_size_request (spin_heure, 60, 27);

  spin_minute_adj = gtk_adjustment_new (30, 0, 59, 1, 10, 10);
  spin_minute = gtk_spin_button_new (GTK_ADJUSTMENT (spin_minute_adj), 1, 0);
  gtk_widget_show (spin_minute);
  gtk_fixed_put (GTK_FIXED (fixed6), spin_minute, 240, 344);
  gtk_widget_set_size_request (spin_minute, 60, 27);

  label50 = gtk_label_new (_("min"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed6), label50, 288, 344);
  gtk_widget_set_size_request (label50, 56, 25);

  label48 = gtk_label_new (_("TEMPS :"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed6), label48, 48, 344);
  gtk_widget_set_size_request (label48, 96, 32);

  label47 = gtk_label_new (_("DATE  :"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed6), label47, 8, 288);
  gtk_widget_set_size_request (label47, 176, 40);

  label52 = gtk_label_new (_("ID d\342\200\231entra\303\256neur :"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed6), label52, 48, 176);
  gtk_widget_set_size_request (label52, 152, 40);

  entry_id_inscription = gtk_entry_new ();
  gtk_widget_show (entry_id_inscription);
  gtk_fixed_put (GTK_FIXED (fixed6), entry_id_inscription, 200, 184);
  gtk_widget_set_size_request (entry_id_inscription, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_inscription), 8226);

  label49 = gtk_label_new (_("hr"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed6), label49, 200, 344);
  gtk_widget_set_size_request (label49, 48, 25);

  label_message_inscription = gtk_label_new ("");
  gtk_widget_show (label_message_inscription);
  gtk_fixed_put (GTK_FIXED (fixed6), label_message_inscription, 0, 384);
  gtk_widget_set_size_request (label_message_inscription, 448, 48);

  btn_ajouter_inscription = gtk_button_new ();
  gtk_widget_show (btn_ajouter_inscription);
  gtk_fixed_put (GTK_FIXED (fixed6), btn_ajouter_inscription, 112, 440);
  gtk_widget_set_size_request (btn_ajouter_inscription, 240, 56);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (btn_ajouter_inscription), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("inscrit"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox17), label51, FALSE, FALSE, 0);

  label53 = gtk_label_new (_("Liste des inscriptions :"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed6), label53, 24, 472);
  gtk_widget_set_size_request (label53, 152, 224);
  gtk_label_set_line_wrap (GTK_LABEL (label53), TRUE);

  btn_retour_inscription = gtk_button_new ();
  gtk_widget_show (btn_retour_inscription);
  gtk_fixed_put (GTK_FIXED (fixed6), btn_retour_inscription, 176, 504);
  gtk_widget_set_size_request (btn_retour_inscription, 112, 48);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (btn_retour_inscription), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox16), label45, FALSE, FALSE, 0);

  label46 = gtk_label_new (_("Sp\303\251cialit\303\251 d\342\200\231entra\303\256neur :"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed6), label46, 0, 232);
  gtk_widget_set_size_request (label46, 208, 32);

  combo_specialite = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combo_specialite);
  gtk_fixed_put (GTK_FIXED (fixed6), combo_specialite, 200, 232);
  gtk_widget_set_size_request (combo_specialite, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_specialite), _("Fitness & Musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_specialite), _("Sports Collectifs"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_specialite), _("Arts Martiaux & Sports de Combat"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_specialite), _("Danse & Mouvement"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_specialite), _("R\303\251\303\251ducation / Pr\303\251paration Physique"));

  label40 = gtk_label_new (_("INSCRIPTION DANS UN CENTRE"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed6), label40, 0, 0);
  gtk_widget_set_size_request (label40, 456, 80);
  gtk_misc_set_padding (GTK_MISC (label40), 3, 0);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_fixed_put (GTK_FIXED (fixed6), scrolledwindow4, 8, 616);
  gtk_widget_set_size_request (scrolledwindow4, 472, 112);

  treeview_inscription = gtk_tree_view_new ();
  gtk_widget_show (treeview_inscription);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), treeview_inscription);
  gtk_widget_set_size_request (treeview_inscription, 448, 96);

  combo_nom_centre = gtk_combo_box_new_text ();
  gtk_widget_show (combo_nom_centre);
  gtk_fixed_put (GTK_FIXED (fixed6), combo_nom_centre, 184, 88);
  gtk_widget_set_size_request (combo_nom_centre, 200, 31);

  entry_adresse_inscription = gtk_combo_box_entry_new_text ();
  gtk_widget_show (entry_adresse_inscription);
  gtk_fixed_put (GTK_FIXED (fixed6), entry_adresse_inscription, 192, 136);
  gtk_widget_set_size_request (entry_adresse_inscription, 189, 29);

  btn_adresse = gtk_button_new ();
  gtk_widget_show (btn_adresse);
  gtk_fixed_put (GTK_FIXED (fixed6), btn_adresse, 400, 80);
  gtk_widget_set_size_request (btn_adresse, 48, 40);

  image25 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_container_add (GTK_CONTAINER (btn_adresse), image25);

  g_signal_connect ((gpointer) btn_ajouter_inscription, "clicked",
                    G_CALLBACK (on_btn_ajouter_inscription_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_retour_inscription, "clicked",
                    G_CALLBACK (on_btn_retour_inscription_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_inscription, "row_activated",
                    G_CALLBACK (on_treeview_inscription_row_activated),
                    NULL);
  g_signal_connect ((gpointer) btn_adresse, "clicked",
                    G_CALLBACK (on_btn_adresse_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window6, window6, "window6");
  GLADE_HOOKUP_OBJECT (window6, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window6, label41, "label41");
  GLADE_HOOKUP_OBJECT (window6, label42, "label42");
  GLADE_HOOKUP_OBJECT (window6, spin_jour, "spin_jour");
  GLADE_HOOKUP_OBJECT (window6, spin_mois, "spin_mois");
  GLADE_HOOKUP_OBJECT (window6, spin_annee, "spin_annee");
  GLADE_HOOKUP_OBJECT (window6, spin_heure, "spin_heure");
  GLADE_HOOKUP_OBJECT (window6, spin_minute, "spin_minute");
  GLADE_HOOKUP_OBJECT (window6, label50, "label50");
  GLADE_HOOKUP_OBJECT (window6, label48, "label48");
  GLADE_HOOKUP_OBJECT (window6, label47, "label47");
  GLADE_HOOKUP_OBJECT (window6, label52, "label52");
  GLADE_HOOKUP_OBJECT (window6, entry_id_inscription, "entry_id_inscription");
  GLADE_HOOKUP_OBJECT (window6, label49, "label49");
  GLADE_HOOKUP_OBJECT (window6, label_message_inscription, "label_message_inscription");
  GLADE_HOOKUP_OBJECT (window6, btn_ajouter_inscription, "btn_ajouter_inscription");
  GLADE_HOOKUP_OBJECT (window6, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window6, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window6, image17, "image17");
  GLADE_HOOKUP_OBJECT (window6, label51, "label51");
  GLADE_HOOKUP_OBJECT (window6, label53, "label53");
  GLADE_HOOKUP_OBJECT (window6, btn_retour_inscription, "btn_retour_inscription");
  GLADE_HOOKUP_OBJECT (window6, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window6, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window6, image16, "image16");
  GLADE_HOOKUP_OBJECT (window6, label45, "label45");
  GLADE_HOOKUP_OBJECT (window6, label46, "label46");
  GLADE_HOOKUP_OBJECT (window6, combo_specialite, "combo_specialite");
  GLADE_HOOKUP_OBJECT (window6, label40, "label40");
  GLADE_HOOKUP_OBJECT (window6, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (window6, treeview_inscription, "treeview_inscription");
  GLADE_HOOKUP_OBJECT (window6, combo_nom_centre, "combo_nom_centre");
  GLADE_HOOKUP_OBJECT (window6, entry_adresse_inscription, "entry_adresse_inscription");
  GLADE_HOOKUP_OBJECT (window6, btn_adresse, "btn_adresse");
  GLADE_HOOKUP_OBJECT (window6, image25, "image25");

  return window6;
}

GtkWidget*
create_window7 (void)
{
  GtkWidget *window7;
  GtkWidget *fixed7;
  GtkWidget *label55;
  GtkWidget *label56;
  GtkWidget *label_nbre_total;
  GtkWidget *label_centre_populaire;
  GtkWidget *btn_retour_stats;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label60;
  GtkWidget *label54;
  GtkWidget *label59;
  GtkWidget *scrolledwindow5;
  GtkWidget *treeview_stats;

  window7 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window7), _("window7"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window7), fixed7);

  label55 = gtk_label_new (_("nombre total des centre :"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed7), label55, 24, 80);
  gtk_widget_set_size_request (label55, 184, 40);

  label56 = gtk_label_new (_("le centre le plus populaire :"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed7), label56, 0, 120);
  gtk_widget_set_size_request (label56, 232, 40);

  label_nbre_total = gtk_label_new ("");
  gtk_widget_show (label_nbre_total);
  gtk_fixed_put (GTK_FIXED (fixed7), label_nbre_total, 208, 88);
  gtk_widget_set_size_request (label_nbre_total, 208, 32);

  label_centre_populaire = gtk_label_new ("");
  gtk_widget_show (label_centre_populaire);
  gtk_fixed_put (GTK_FIXED (fixed7), label_centre_populaire, 208, 120);
  gtk_widget_set_size_request (label_centre_populaire, 224, 32);

  btn_retour_stats = gtk_button_new ();
  gtk_widget_show (btn_retour_stats);
  gtk_fixed_put (GTK_FIXED (fixed7), btn_retour_stats, 128, 432);
  gtk_widget_set_size_request (btn_retour_stats, 200, 64);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (btn_retour_stats), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label60 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox18), label60, FALSE, FALSE, 0);

  label54 = gtk_label_new (_("STATS"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed7), label54, 0, 0);
  gtk_widget_set_size_request (label54, 456, 80);
  gtk_misc_set_padding (GTK_MISC (label54), 3, 0);

  label59 = gtk_label_new (_("liste d'inscription par centre :"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed7), label59, 16, 200);
  gtk_widget_set_size_request (label59, 328, 40);
  gtk_label_set_line_wrap (GTK_LABEL (label59), TRUE);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_fixed_put (GTK_FIXED (fixed7), scrolledwindow5, 8, 248);
  gtk_widget_set_size_request (scrolledwindow5, 450, 150);

  treeview_stats = gtk_tree_view_new ();
  gtk_widget_show (treeview_stats);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), treeview_stats);
  gtk_widget_set_size_request (treeview_stats, 448, 144);

  g_signal_connect ((gpointer) btn_retour_stats, "clicked",
                    G_CALLBACK (on_btn_retour_stats_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_stats, "row_activated",
                    G_CALLBACK (on_treeview_stats_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window7, window7, "window7");
  GLADE_HOOKUP_OBJECT (window7, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window7, label55, "label55");
  GLADE_HOOKUP_OBJECT (window7, label56, "label56");
  GLADE_HOOKUP_OBJECT (window7, label_nbre_total, "label_nbre_total");
  GLADE_HOOKUP_OBJECT (window7, label_centre_populaire, "label_centre_populaire");
  GLADE_HOOKUP_OBJECT (window7, btn_retour_stats, "btn_retour_stats");
  GLADE_HOOKUP_OBJECT (window7, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (window7, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (window7, image18, "image18");
  GLADE_HOOKUP_OBJECT (window7, label60, "label60");
  GLADE_HOOKUP_OBJECT (window7, label54, "label54");
  GLADE_HOOKUP_OBJECT (window7, label59, "label59");
  GLADE_HOOKUP_OBJECT (window7, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (window7, treeview_stats, "treeview_stats");

  return window7;
}

GtkWidget*
create_window8 (void)
{
  GtkWidget *window8;
  GtkWidget *fixed8;
  GtkWidget *label61;
  GtkWidget *btn_window_ajouter;
  GtkWidget *btn_window_modifier;
  GtkWidget *btn_window_supprimer;
  GtkWidget *btn_window_rechercher;
  GtkWidget *btn_window_stats;
  GtkWidget *btn_retour_navigation;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label62;

  window8 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window8), _("window8"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (window8), fixed8);

  label61 = gtk_label_new (_("NAVIGATION"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed8), label61, 0, 0);
  gtk_widget_set_size_request (label61, 456, 80);
  gtk_misc_set_padding (GTK_MISC (label61), 3, 0);

  btn_window_ajouter = gtk_button_new_with_mnemonic (_("ajouter un centre"));
  gtk_widget_show (btn_window_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed8), btn_window_ajouter, 0, 80);
  gtk_widget_set_size_request (btn_window_ajouter, 456, 72);

  btn_window_modifier = gtk_button_new_with_mnemonic (_("modifier un centre"));
  gtk_widget_show (btn_window_modifier);
  gtk_fixed_put (GTK_FIXED (fixed8), btn_window_modifier, 0, 160);
  gtk_widget_set_size_request (btn_window_modifier, 456, 72);

  btn_window_supprimer = gtk_button_new_with_mnemonic (_("supprimer un centre "));
  gtk_widget_show (btn_window_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed8), btn_window_supprimer, 0, 240);
  gtk_widget_set_size_request (btn_window_supprimer, 456, 72);

  btn_window_rechercher = gtk_button_new_with_mnemonic (_("rechercher un centre"));
  gtk_widget_show (btn_window_rechercher);
  gtk_fixed_put (GTK_FIXED (fixed8), btn_window_rechercher, 0, 320);
  gtk_widget_set_size_request (btn_window_rechercher, 456, 72);

  btn_window_stats = gtk_button_new_with_mnemonic (_("STATS"));
  gtk_widget_show (btn_window_stats);
  gtk_fixed_put (GTK_FIXED (fixed8), btn_window_stats, 0, 400);
  gtk_widget_set_size_request (btn_window_stats, 456, 72);

  btn_retour_navigation = gtk_button_new ();
  gtk_widget_show (btn_retour_navigation);
  gtk_fixed_put (GTK_FIXED (fixed8), btn_retour_navigation, 152, 496);
  gtk_widget_set_size_request (btn_retour_navigation, 144, 56);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (btn_retour_navigation), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label62 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (hbox19), label62, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) btn_window_ajouter, "clicked",
                    G_CALLBACK (on_btn_window_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_window_modifier, "clicked",
                    G_CALLBACK (on_btn_window_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_window_supprimer, "clicked",
                    G_CALLBACK (on_btn_window_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_window_rechercher, "clicked",
                    G_CALLBACK (on_btn_window_rechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_window_stats, "clicked",
                    G_CALLBACK (on_btn_window_stats_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_retour_navigation, "clicked",
                    G_CALLBACK (on_btn_retour_navigation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window8, window8, "window8");
  GLADE_HOOKUP_OBJECT (window8, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window8, label61, "label61");
  GLADE_HOOKUP_OBJECT (window8, btn_window_ajouter, "btn_window_ajouter");
  GLADE_HOOKUP_OBJECT (window8, btn_window_modifier, "btn_window_modifier");
  GLADE_HOOKUP_OBJECT (window8, btn_window_supprimer, "btn_window_supprimer");
  GLADE_HOOKUP_OBJECT (window8, btn_window_rechercher, "btn_window_rechercher");
  GLADE_HOOKUP_OBJECT (window8, btn_window_stats, "btn_window_stats");
  GLADE_HOOKUP_OBJECT (window8, btn_retour_navigation, "btn_retour_navigation");
  GLADE_HOOKUP_OBJECT (window8, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (window8, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (window8, image19, "image19");
  GLADE_HOOKUP_OBJECT (window8, label62, "label62");

  return window8;
}

GtkWidget*
create_window9 (void)
{
  GtkWidget *window9;
  GtkWidget *fixed9;
  GtkWidget *entry1;
  GtkWidget *label602;
  GtkWidget *entry2;
  GtkWidget *label603;
  GtkWidget *btn_login;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label604;
  GtkWidget *label_msg_login;
  GtkWidget *label601;
  GtkWidget *btn_sign_up;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label616;

  window9 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window9), _("window9"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (window9), fixed9);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed9), entry1, 176, 72);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  label602 = gtk_label_new (_("Username : "));
  gtk_widget_show (label602);
  gtk_fixed_put (GTK_FIXED (fixed9), label602, 48, 64);
  gtk_widget_set_size_request (label602, 152, 40);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed9), entry2, 176, 120);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label603 = gtk_label_new (_("Password :"));
  gtk_widget_show (label603);
  gtk_fixed_put (GTK_FIXED (fixed9), label603, 40, 112);
  gtk_widget_set_size_request (label603, 152, 40);

  btn_login = gtk_button_new ();
  gtk_widget_show (btn_login);
  gtk_fixed_put (GTK_FIXED (fixed9), btn_login, 104, 224);
  gtk_widget_set_size_request (btn_login, 256, 56);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (btn_login), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label604 = gtk_label_new_with_mnemonic (_(" LOGIN"));
  gtk_widget_show (label604);
  gtk_box_pack_start (GTK_BOX (hbox20), label604, FALSE, FALSE, 0);

  label_msg_login = gtk_label_new ("");
  gtk_widget_show (label_msg_login);
  gtk_fixed_put (GTK_FIXED (fixed9), label_msg_login, 24, 160);
  gtk_widget_set_size_request (label_msg_login, 424, 48);

  label601 = gtk_label_new ("");
  gtk_widget_show (label601);
  gtk_fixed_put (GTK_FIXED (fixed9), label601, 0, 0);
  gtk_widget_set_size_request (label601, 456, 80);
  gtk_misc_set_padding (GTK_MISC (label601), 3, 0);

  btn_sign_up = gtk_button_new ();
  gtk_widget_show (btn_sign_up);
  gtk_fixed_put (GTK_FIXED (fixed9), btn_sign_up, 152, 288);
  gtk_widget_set_size_request (btn_sign_up, 160, 56);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (btn_sign_up), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label616 = gtk_label_new_with_mnemonic (_(" SIGNUP"));
  gtk_widget_show (label616);
  gtk_box_pack_start (GTK_BOX (hbox23), label616, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) btn_login, "clicked",
                    G_CALLBACK (on_btn_login_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_sign_up, "clicked",
                    G_CALLBACK (on_btn_sign_up_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window9, window9, "window9");
  GLADE_HOOKUP_OBJECT (window9, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window9, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window9, label602, "label602");
  GLADE_HOOKUP_OBJECT (window9, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window9, label603, "label603");
  GLADE_HOOKUP_OBJECT (window9, btn_login, "btn_login");
  GLADE_HOOKUP_OBJECT (window9, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (window9, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (window9, image20, "image20");
  GLADE_HOOKUP_OBJECT (window9, label604, "label604");
  GLADE_HOOKUP_OBJECT (window9, label_msg_login, "label_msg_login");
  GLADE_HOOKUP_OBJECT (window9, label601, "label601");
  GLADE_HOOKUP_OBJECT (window9, btn_sign_up, "btn_sign_up");
  GLADE_HOOKUP_OBJECT (window9, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (window9, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (window9, image23, "image23");
  GLADE_HOOKUP_OBJECT (window9, label616, "label616");

  return window9;
}

GtkWidget*
create_window10 (void)
{
  GtkWidget *window10;
  GtkWidget *fixed10;
  GtkWidget *entry_nom;
  GtkWidget *entry_prenom;
  GtkWidget *entry_email_insc;
  GtkWidget *entry_tel_insc;
  GtkWidget *label606;
  GtkWidget *label607;
  GtkWidget *label608;
  GtkWidget *label609;
  GtkWidget *entry_user;
  GtkWidget *entry_pass;
  GtkWidget *label610;
  GtkWidget *label611;
  GtkWidget *label612;
  GtkWidget *label613;
  GtkObject *spin_age_adj;
  GtkWidget *spin_age;
  GtkWidget *combo_role;
  GtkWidget *label605;
  GtkWidget *btn_retour;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label615;
  GtkWidget *btn_inscrit;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label614;
  GtkWidget *label_msg_insc;

  window10 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window10), _("window10"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (window10), fixed10);

  entry_nom = gtk_entry_new ();
  gtk_widget_show (entry_nom);
  gtk_fixed_put (GTK_FIXED (fixed10), entry_nom, 152, 72);
  gtk_widget_set_size_request (entry_nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom), 8226);

  entry_prenom = gtk_entry_new ();
  gtk_widget_show (entry_prenom);
  gtk_fixed_put (GTK_FIXED (fixed10), entry_prenom, 152, 112);
  gtk_widget_set_size_request (entry_prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom), 8226);

  entry_email_insc = gtk_entry_new ();
  gtk_widget_show (entry_email_insc);
  gtk_fixed_put (GTK_FIXED (fixed10), entry_email_insc, 152, 200);
  gtk_widget_set_size_request (entry_email_insc, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_email_insc), 8226);

  entry_tel_insc = gtk_entry_new ();
  gtk_widget_show (entry_tel_insc);
  gtk_fixed_put (GTK_FIXED (fixed10), entry_tel_insc, 152, 240);
  gtk_widget_set_size_request (entry_tel_insc, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_tel_insc), 8226);

  label606 = gtk_label_new (_("NOM : "));
  gtk_widget_show (label606);
  gtk_fixed_put (GTK_FIXED (fixed10), label606, 48, 64);
  gtk_widget_set_size_request (label606, 152, 40);

  label607 = gtk_label_new (_("PRENOM :"));
  gtk_widget_show (label607);
  gtk_fixed_put (GTK_FIXED (fixed10), label607, 32, 104);
  gtk_widget_set_size_request (label607, 152, 40);

  label608 = gtk_label_new (_("AGE :"));
  gtk_widget_show (label608);
  gtk_fixed_put (GTK_FIXED (fixed10), label608, 40, 144);
  gtk_widget_set_size_request (label608, 152, 40);

  label609 = gtk_label_new (_("E-MAIL :"));
  gtk_widget_show (label609);
  gtk_fixed_put (GTK_FIXED (fixed10), label609, 32, 192);
  gtk_widget_set_size_request (label609, 160, 40);

  entry_user = gtk_entry_new ();
  gtk_widget_show (entry_user);
  gtk_fixed_put (GTK_FIXED (fixed10), entry_user, 152, 280);
  gtk_widget_set_size_request (entry_user, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_user), 8226);

  entry_pass = gtk_entry_new ();
  gtk_widget_show (entry_pass);
  gtk_fixed_put (GTK_FIXED (fixed10), entry_pass, 152, 328);
  gtk_widget_set_size_request (entry_pass, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_pass), 8226);

  label610 = gtk_label_new (_("TEL :"));
  gtk_widget_show (label610);
  gtk_fixed_put (GTK_FIXED (fixed10), label610, 40, 232);
  gtk_widget_set_size_request (label610, 160, 40);

  label611 = gtk_label_new (_("USERNAME :"));
  gtk_widget_show (label611);
  gtk_fixed_put (GTK_FIXED (fixed10), label611, 16, 272);
  gtk_widget_set_size_request (label611, 160, 40);

  label612 = gtk_label_new (_("PASSWORD :"));
  gtk_widget_show (label612);
  gtk_fixed_put (GTK_FIXED (fixed10), label612, 16, 320);
  gtk_widget_set_size_request (label612, 160, 40);

  label613 = gtk_label_new (_("ROLE :"));
  gtk_widget_show (label613);
  gtk_fixed_put (GTK_FIXED (fixed10), label613, 16, 368);
  gtk_widget_set_size_request (label613, 160, 40);

  spin_age_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spin_age = gtk_spin_button_new (GTK_ADJUSTMENT (spin_age_adj), 1, 0);
  gtk_widget_show (spin_age);
  gtk_fixed_put (GTK_FIXED (fixed10), spin_age, 152, 152);
  gtk_widget_set_size_request (spin_age, 60, 27);

  combo_role = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combo_role);
  gtk_fixed_put (GTK_FIXED (fixed10), combo_role, 128, 376);
  gtk_widget_set_size_request (combo_role, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_role), _("ADMIN"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_role), _("ENTRAINEUR"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_role), _("MEMBRE"));

  label605 = gtk_label_new (_("INSCRIPTION"));
  gtk_widget_show (label605);
  gtk_fixed_put (GTK_FIXED (fixed10), label605, 0, 0);
  gtk_widget_set_size_request (label605, 456, 80);
  gtk_misc_set_padding (GTK_MISC (label605), 3, 1);

  btn_retour = gtk_button_new ();
  gtk_widget_show (btn_retour);
  gtk_fixed_put (GTK_FIXED (fixed10), btn_retour, 152, 536);
  gtk_widget_set_size_request (btn_retour, 128, 48);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (btn_retour), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label615 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label615);
  gtk_box_pack_start (GTK_BOX (hbox22), label615, FALSE, FALSE, 0);

  btn_inscrit = gtk_button_new ();
  gtk_widget_show (btn_inscrit);
  gtk_fixed_put (GTK_FIXED (fixed10), btn_inscrit, 72, 480);
  gtk_widget_set_size_request (btn_inscrit, 320, 48);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (btn_inscrit), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label614 = gtk_label_new_with_mnemonic (_(" inscrit"));
  gtk_widget_show (label614);
  gtk_box_pack_start (GTK_BOX (hbox21), label614, FALSE, FALSE, 0);

  label_msg_insc = gtk_label_new ("");
  gtk_widget_show (label_msg_insc);
  gtk_fixed_put (GTK_FIXED (fixed10), label_msg_insc, 0, 424);
  gtk_widget_set_size_request (label_msg_insc, 448, 48);

  g_signal_connect ((gpointer) btn_retour, "clicked",
                    G_CALLBACK (on_btn_retour_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_inscrit, "clicked",
                    G_CALLBACK (on_btn_inscrit_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window10, window10, "window10");
  GLADE_HOOKUP_OBJECT (window10, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window10, entry_nom, "entry_nom");
  GLADE_HOOKUP_OBJECT (window10, entry_prenom, "entry_prenom");
  GLADE_HOOKUP_OBJECT (window10, entry_email_insc, "entry_email_insc");
  GLADE_HOOKUP_OBJECT (window10, entry_tel_insc, "entry_tel_insc");
  GLADE_HOOKUP_OBJECT (window10, label606, "label606");
  GLADE_HOOKUP_OBJECT (window10, label607, "label607");
  GLADE_HOOKUP_OBJECT (window10, label608, "label608");
  GLADE_HOOKUP_OBJECT (window10, label609, "label609");
  GLADE_HOOKUP_OBJECT (window10, entry_user, "entry_user");
  GLADE_HOOKUP_OBJECT (window10, entry_pass, "entry_pass");
  GLADE_HOOKUP_OBJECT (window10, label610, "label610");
  GLADE_HOOKUP_OBJECT (window10, label611, "label611");
  GLADE_HOOKUP_OBJECT (window10, label612, "label612");
  GLADE_HOOKUP_OBJECT (window10, label613, "label613");
  GLADE_HOOKUP_OBJECT (window10, spin_age, "spin_age");
  GLADE_HOOKUP_OBJECT (window10, combo_role, "combo_role");
  GLADE_HOOKUP_OBJECT (window10, label605, "label605");
  GLADE_HOOKUP_OBJECT (window10, btn_retour, "btn_retour");
  GLADE_HOOKUP_OBJECT (window10, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (window10, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (window10, image22, "image22");
  GLADE_HOOKUP_OBJECT (window10, label615, "label615");
  GLADE_HOOKUP_OBJECT (window10, btn_inscrit, "btn_inscrit");
  GLADE_HOOKUP_OBJECT (window10, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (window10, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (window10, image21, "image21");
  GLADE_HOOKUP_OBJECT (window10, label614, "label614");
  GLADE_HOOKUP_OBJECT (window10, label_msg_insc, "label_msg_insc");

  return window10;
}

GtkWidget*
create_window11 (void)
{
  GtkWidget *window11;
  GtkWidget *fixed11;
  GtkWidget *label_authen;
  GtkWidget *label617;

  window11 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window11), _("window11"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (window11), fixed11);

  label_authen = gtk_label_new ("");
  gtk_widget_show (label_authen);
  gtk_fixed_put (GTK_FIXED (fixed11), label_authen, 0, 48);
  gtk_widget_set_size_request (label_authen, 456, 80);
  gtk_misc_set_padding (GTK_MISC (label_authen), 3, 1);

  label617 = gtk_label_new ("");
  gtk_widget_show (label617);
  gtk_fixed_put (GTK_FIXED (fixed11), label617, 8, 160);
  gtk_widget_set_size_request (label617, 432, 80);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window11, window11, "window11");
  GLADE_HOOKUP_OBJECT (window11, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (window11, label_authen, "label_authen");
  GLADE_HOOKUP_OBJECT (window11, label617, "label617");

  return window11;
}

GtkWidget*
create_window12 (void)
{
  GtkWidget *window12;
  GtkWidget *fixed12;
  GtkWidget *label_resultat;
  GtkWidget *btn_ok;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image24;
  GtkWidget *label618;

  window12 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window12), _("window12"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (window12), fixed12);

  label_resultat = gtk_label_new ("");
  gtk_widget_show (label_resultat);
  gtk_fixed_put (GTK_FIXED (fixed12), label_resultat, 32, 0);
  gtk_widget_set_size_request (label_resultat, 344, 440);

  btn_ok = gtk_button_new ();
  gtk_widget_show (btn_ok);
  gtk_fixed_put (GTK_FIXED (fixed12), btn_ok, 112, 440);
  gtk_widget_set_size_request (btn_ok, 176, 56);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (btn_ok), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image24 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox24), image24, FALSE, FALSE, 0);

  label618 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label618);
  gtk_box_pack_start (GTK_BOX (hbox24), label618, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) btn_ok, "clicked",
                    G_CALLBACK (on_btn_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window12, window12, "window12");
  GLADE_HOOKUP_OBJECT (window12, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (window12, label_resultat, "label_resultat");
  GLADE_HOOKUP_OBJECT (window12, btn_ok, "btn_ok");
  GLADE_HOOKUP_OBJECT (window12, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (window12, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (window12, image24, "image24");
  GLADE_HOOKUP_OBJECT (window12, label618, "label618");

  return window12;
}

